python generate_simple.py \
    --use_prompt \
    --benchmark gsm8k \
    --num_samples 20000 \
    --remasking entropy \
    --steps 256 \
    --gen_length 256 \
    --block_length 256 \
    --batch_size 8 \
    --device cuda:0 cuda:1 cuda:2 cuda:3 cuda:4 cuda:5 \
    --logits_eos_inf \
    --use_ensemble_model \
    --output_dir ./result \
    --exp_name gsm8k_dropout0.1_only_last_layer_entropy_all \
    --dropout_p 0.1
